### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by SolarEagle777** [khjde1207/khjde1207.github.io#1]
I am not able to access to site version which is khjde1207.github.io through any of my devices. The only version that works is app version but I need to use web version of it. Is there any ways I can resolve this problem?

**Comment by khjde1207** [comment]
Sorry, there was some logic that didn't work on the web.
I fixed that part.
Press ctrl+r to refresh.

**Comment by SolarEagle777** [comment]
Oh It works. Thank you so much. This is so useful site. I'm using it everyday. Thanks a lot.

**Comment by khjde1207** [comment]
Thank you for using it.
